#!/bin/env python

import sys

class INT2IP():
    _segs = list()
    def __init__(self, number):
        if number > 4294967295 or number < 0:
            print "Error: Number is out of ipv4 range!"
            sys.exit(1)
        self._number = number
    def int2ip(self):
        for i in range(4):
            self._segs.append(str(self._number%256))
            self._number /= 256
        ip = ".".join(self._segs[::-1])
        return ip


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print "Syntax Error: int2ip need an argumnet"
        sys.exit(1)
    try:
        number = int(sys.argv[1])
    except:
        print "Error: Argument need to be a number!"
        sys.exit(2)
    print INT2IP(number).int2ip()
